const booksData = [
  {
    title: "Journey of the Pharaohs",
    author: "Clive Cussler",
    series: "Numa Files",
    imgSrc:
      "https://m.media-amazon.com/images/I/91e9bvCiTQL._AC_UF1000,1000_QL80_.jpg",
    year: "2023",
    review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    stars: 3,
  },
  {
    title: "Pimeitten vetten paholainen",
    author: "Stuart Turton",
    imgSrc:
      "https://m.media-amazon.com/images/I/91QCG8hNfVL._AC_UF1000,1000_QL80_.jpg",
    year: "2023",
    review: "4/5, a happily evil ending",
    stars: 4,
  },
  {
    title: "Voidgod",
    series: "Savage Dominion #3",
    author: "G. D. Penman and Luke Chmilenko",
    imgSrc: "https://m.media-amazon.com/images/I/51V1k-44XdL.jpg",
    year: "2023",
    review: "5/5, this will make you cry",
    stars: 5,
  },
  {
    title: "Oh God, Not Again",
    author: "Sarah1281",
    year: "2023",
    review: "3/5, I literally don't remember",
    stars: 3,
  },
  {
    title: "Vanki nimeltä Papillon",
    author: "Henri Charrière",
    year: "2023",
    review: "3/5, feels like it didn't do what it promised",
    stars: 3.5,
    imgSrc: "https://upload.wikimedia.org/wikipedia/fi/6/65/Papillonkirja.jpg",
  },
  {
    title: "Children of Hope ",
    series: "Seafort Saga #7",
    author: "David Feintuch",
    year: "2023",
    review: "3/5, the new main character pales in comparison to the old",
    stars: 3,
    imgSrc: "https://m.media-amazon.com/images/I/51VX-WfD4vL.jpg",
  },
  {
    title: "Avaruuslaivan kadetti",
    author: "Robert Heinlen",
    year: "2023",
    review: "3/5, hasn't aged well",
    stars: 3,
    imgSrc: "https://upload.wikimedia.org/wikipedia/en/2/20/Sc48.jpg",
  },
  {
    title: "Patriarch's Hope",
    series: "Seafort Saga #6",
    author: "David Feintuch",
    year: "2023",
    review: "4/5, it'll make you cry",
    stars: 4.5,
  },
  {
    title: "Voices of Hope",
    series: "Seafort Saga #5",
    author: "David Feintuch",
    year: "2023",
    stars: 2,
  },
  {
    title: "Doll in the Jewellery Box",
    author: "Stitchgunk",
    year: "2023",
    stars: 5,
  },
  {
    title: "Pohjolan joulu, perinteitä kekristä nuuttiin",
    author: "Aki Pulkkanen",
    year: "2023",
    stars: 3,
  },
  {
    title: "A Soul to Keep",
    author: "Opal Reyne",
    year: "2023",
    stars: 1,
  },
  {
    title: "The Stainless Steel Rat Goes to Hell",
    series: "The Stainless Steel Rat Series",
    author: "Harry Harrison",
    year: "2023",
    stars: 4,
  },
  {
    title: "The Stainless Steel Rat Joins the Circus",
    series: "The Stainless Steel Rat Series",
    author: "Harry Harrison",
    year: "2023",
    stars: 3,
  },
  {
    title: "The Stainless Steel Rat Gets Drafted",
    series: "The Stainless Steel Rat Series",
    author: "Harry Harrison",
    year: "2023",
    stars: 5,
  },
  {
    title: "Tuntematon kersantti",
    author: "Lasse Lehtinen",
    year: "2023",
    stars: 5,
  },
  {
    title: "Sniper One",
    author: "D. A. N. Mills",
    year: "2023",
    stars: 3,
  },
  {
    title: "Teräsrotta presidentiksi",
    series: "The Stainless Steel Rat Series",
    author: "Harry Harrison",
    year: "2023",
    stars: 5,
  },
  {
    title: "Rebirth",
    series: "Necrotic Apocalypse #5",
    author: "David Petrie",
    year: "2023",
    stars: 3,
  },
  {
    title: "Morsianten laiva",
    author: "Jojo Moyes",
    year: "2023",
    stars: 3,
  },
  {
    title: "Sydämiä seireeneille",
    series: "Suomea lohikäärmeille #2",
    author: "Briitta Hepo-oja",
    year: "2023",
    stars: 3,
  },
  {
    title: "Suomea lohikäärmeille",
    series: "Suomea lohikäärmeille #1",
    author: "Briitta Hepo-oja",
    year: "2023",
    stars: 5,
  },
  {
    title: "Life Reset",
    series: "New Era Online #1",
    author: "Shemer Kuznits",
    year: "2023",
    stars: 4,
  },
];

export default booksData;
